name: Deploy to Sonatype

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-26
    timeout-minutes: 30
    env:
      TERM: dumb

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
           distribution: 'temurin' # See 'Supported distributions' for available options
           java-version: '17'
      - name: Configure GPG Key
        run: |
          mkdir ~/.gpgkey
          echo $GPG_KEY > ~/.gpgkey/secring.gpg.b64
          base64 -d -i ~/.gpgkey/secring.gpg.b64 -o ~/.gpgkey/secring.gpg
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
      - name:  Deploy to Sonatype
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: |
          ./gradlew publishToMavenCentral --no-daemon -Psigning.keyId=${{secrets.GPG_KEY_ID}} -Psigning.password=${{secrets.GPG_KEY_PASSWORD}} -Psigning.secretKeyRingFile=$(echo ~/.gpgkey/secring.gpg)
